# Tells Travis we're running on a Node environment
language: node_js
node_js: '8'
cache: yarn

install:
  - yarn install

jobs:
  include:
    # Run the entire test suite
    - stage: test
    - script:
        - yarn test
        - yarn coverage
      name: 'Run Tests & Coverage'

    # Build the components for npm registry
    # Build the documentation website
    - stage: build
    - script:
        - yarn build
        # - yarn deploy
      name: 'Build & Deploy Relements'
    - script: yarn build:storybook
      name: 'Build & Deploy Documentation'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static
        repo: pagrawl3/relements
        target_branch: gh-pages
        on:
          branch: master

stages:
  - test
  - build
  - name: publish
    if: branch = master
