# Tells Travis we're running on a Node environment
language: node_js
node_js: '8'
cache: yarn

install:
  - yarn install

jobs:
  include:
    # Run the entire test suite
    - stage: test
    - script: yarn test
      name: 'Run Tests'
    - script: yarn coverage
      name: 'Collect Code Coverage'

    # Build the components for npm registry
    # Build the documentation website
    - stage: build
    - script: yarn build
      name: 'Build Relements'
    - script: yarn build:storybook
      name: 'Build Documentation'

    # Publish the package npm
    # Publish the website on github pages
    - stage: publish
    # - script: yarn deploy
    #   name: 'Publish Relements'
    - script: yarn deploy:storybook
      name: 'Publish Storybook'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static
        repo: pagrawl3/relements
        target_branch: gh-pages
        on:
          branch: master

stages:
  - test
  - build
  - name: publish
    if: branch = master
